
server:
  port: 8080

spring:
  data:
    mongodb:
      database: admin
      port: 27017
      username: user
      password: pass
  application:
    name: spring-cloud-eureka-feign-client  

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false