version: '3.8'
services:
  accendro_chat_web_app_react:
    build:
      context: ./Frontend/accendro_chat_app_react/
      dockerfile: ./Docker/Dockerfile
    ports:
      - "3000:3000"
  
  websocket-chat-service:
    build:
      context: ./Backend/WebSocketChatService/WebSocketChatService/target/
      dockerfile: ../Docker/Dockerfile
    image: websocket-chat-service:latest
    container_name: websocket-chat-service
    restart: always
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    expose:
      - 27018
    command: --quiet

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8090:8090
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb


  authentication-chat-service:
    build:
      context: ./Backend/UsersService/UserService/target/
      dockerfile: ../Docker/Dockerfile
    image: authentication-chat-service:latest
    container_name: authentication-chat-service
    restart: always
    ports:
      - "8081:8081"
    expose:
      - 8081