version: "3.8"

services:

  authentication-chat-service:
    build:
      context: ../target/
      dockerfile: ../Docker/Dockerfile
    image: authentication-chat-service:latest
    container_name: authentication-chat-service
    restart: always
    ports:
      - "8081:8081"
    expose:
      - 8081
