version: "3.8"

services:
  
  authentication-chat-service:
    build:
      context: ../target/
      dockerfile: ../Docker/Dockerfile
    image: authentication-chat-service:latest
    environment: 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE= http://eureka-server-service:8761/eureka/
    container_name: authentication-chat-service
    restart: always
    ports:
      - "8081:8081"
    expose:
      - 8081
    networks:
      - accendro_bridge

networks:
  accendro_bridge:
    external: false
    name: accendro_bridge