version: '3'

services:
  websocket-chat-service:
    build:
      context: ../target/
      dockerfile: ../Docker/Dockerfile
    image: websocket-chat-service:latest
    environment: 
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE= http://eureka-server-service:8761/eureka/
      - MONGODB_URI= mongodb://mongodb:27017/admin
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=true
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=user
      - SPRING_DATA_MONGODB_PASSWORD=pass
      - SPRING_DATA_MONGODB_DATABASE=admin
      - WAIT_HOSTS= mongodb:27017
    container_name: websocket-chat-service
    restart: always
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - mongodb
    networks:
      - accendro_bridge

  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=admin
      - MONGO_DB_USERNAME=user
      - MONGO_DB_PASSWORD=pass
    expose:
      - 27017
    networks:
      - accendro_bridge
    command: --quiet

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8090:8090
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - accendro_bridge
